;-*- mode: MACRO11; tab-width: 8; indent-tabs-mode: t -*-
;
; Self test: after power reset MDCINI works incorrectly
;
	.TITLE	DEQNA logic
	.IDENT	/x01.00/

	.SBTTL	Definitions
DBGINF	= 0
ETHINI	= 0
ETBCHK	= 0
STATNM	= 1

	.SBTTL	- Memory map and registers
;===========================================================================
; Memory addresses
;---------------------------------------------------------------------------
; External bus access
; 174456 - CSR
; 174454 - VAR
; 174450 - RBDL
; 174444 - TBDL
; 174440 - Base address
;
; Internal bus access
; 160000 - 167777 ROM
; 024000 - 024012 BDL block
; 024020 - 024036 DMA registers
; 024040 - 024076 Ethernet registers
; 020000 - 023777 Transmit buffer
; 010000 - 017777 Receive buffer
; 000000 - 007777 RAM with control program
;
;---------------------------------------------------------------------------
; Register definitions
;---------------------------------------------------------------------------
; External registers
;
LQABAS	= 24100	    ; Base address
LQARLL	= LQABAS+4  ; Rx BDL low order address bits
LQARLH	= LQABAS+6  ; Rx BDL high order address bits
LQATLL	= LQABAS+10 ; Tx BDL low order address bits
LQATLH	= LQABAS+12 ; Tx BDL high order address bits
LQAVAR	= LQABAS+14 ; Vector Address Register
LQACSR	= LQABAS+16 ; Control and Status Register
;
; Internal registers
;
RAMTOP	= 010000    ; Upper program limit
;
;---Buffers----
RXBUF	= 10000	    ; Receive buffer address
RXADR	= 10002	    ; Addess register
RXCNF	= 10004	    ; Byte counter and flags
; RO: {2'b0, cmpmac, crc_err, runt_err, rxcntb[10:0]}
RXBSIZ	= 4000	    ; Size of buffer (words)
TXBUF	= 20000	    ; Transmit buffer address
TXBSIZ	= 2000	    ; Size of buffer (words)
;
;----BD ROM----
BDROM	= 160000    ; BD ROM address
BDRSIZ	= 10000	    ; BD ROM size
;
;-----BDL------
BDLBAS	= 24000	    ; BDL buffer address
;	  24012	    ; Last value
;	  24014	    ; Unused
BDLADR	= 24016	    ; Internal address register
;FLGVAL	= 140000    ; Flag value
FLGVAL	= 177777    ; Flag value
;
;-----DMA------
DMAOP 	= 24020	    ; DMA operation/status
DMACNT	= 24022	    ; DMA words counter (2's compl.)
DMALDM	= 24024	    ; DMA internal device multiplexer:
		    ; 0 - no device; 1 - RX buffer; 2 - TX buffer; 3 - BDL buffer
DMAHLA	= 24026	    ; Low bits host memory address
DMAHHA	= 24030     ; High bits host memory address
DMATIM 	= 24032	    ; DMA operation timeout timer
;
;---Ethernet---
ECTST	= 24040	    ; Ethernet control/status bits
; *** read operation ***
; lbyte - {intmode, rxmode, promis, mcast, skipb, stpac, txrdy, rxrdy}
; hbyte - {3'b0, crser, txerg, rxerg, extmode, intextmode};
; *** write operation ***
; lbyte - {2'b0, promis, mcast, skipb, stpac, txrdy, 1'b0}
;--------------
ECNTB	= 24042     ; Bytes counter for transmit operations !!! write only !!!
;--------------
EMDVAL	= 24044     ; Ethernet MD input/output value
;--------------
EMDCTR	= 24046     ; Ethernet MD control/status
; Write operation bits (control)
;  6    : operation (I/O - write/read)
;  5    : set to 1 to start operation
;  4:0  : reg. address
; Read operation bits (status)
;  15   : 1/0 - ready/busy
;  14,13: speed (10-1000; 01-100; 00-10; 11-reserved)
;  12   : duplex (1-full; 0-half)
;  11   : reserved (0)
;  10   : 1-MDI crossover; 0-MDI
;  9    : receiver (1-ready; 0-not ready)
;  8    : link (1-yes; 0-no)
;  7    : reserved (0)
;  6    : operation (1/0 - write/read)
;  5    : set to 1 to start operation
;  4:0  : reg. address
;--------------
EGMOD	= 24050
; read  - {bdroms, 10'b0, stm_res, stm_ena, leds[2:0]}
; write - {11'bx, stm_res, stm_ena, leds[2:0]}
;--------------
ESADR	= 24060     ; +3 - station address + checksum. RO
;--------------
; MAC address table
EMACA	= 24120	    ; Address register
EMAC1	= 24122     ; Low bits section
EMAC2	= 24124     ; Middle bits section
EMAC3	= 24126     ; High bits section
;

	.SBTTL	- Bit definitions
;===========================================================================
; General bit definitions
;---------------------------------------------------------------------------
BT.15	= 100000
BT.14	= 040000
BT.13	= 020000
BT.12	= 010000
BT.11	= 004000
BT.10	= 002000
BT.09	= 001000
BT.08	= 000400
BT.07	= 000200
BT.06	= 000100
BT.05	= 000040
BT.04	= 000020
BT.03	= 000010
BT.02	= 000004
BT.01	= 000002
BT.00	= 000001
;---------------------------------------------------------------------------
;  CSR bit definitions
CS.RI	= BT.15	; Receive interrupt request
CS.SE	= BT.10	; Sanity timer
CS.EL	= BT.09	; External loopback
CS.IL	= BT.08	; Internal loopback
CS.XI	= BT.07	; Transmit interrupt request
CS.IE	= BT.06	; Interrupt enable
CS.RL	= BT.05	; Receive List Invalid/Empty
CS.XL	= BT.04	; Transmit List Invalid/Empty
CS.BD	= BT.03	; Boot/Diagnostic ROM load
CS.NI	= BT.02	; Nonexistance-memory timeout Interrupt
CS.SR	= BT.01	; Software reset
CS.RE	= BT.00	; Receiver enable
;---------------------------------------------------------------------------
; Address descriptor bits
AD.V	= BT.15	; Valid bit
AD.C	= BT.14	; Chain address bit
AD.E	= BT.13	; End of message
AD.S	= BT.12	; Setup package indication
AD.L	= BT.07	; Low byte (termination)
AD.H	= BT.06	; High byte (beginning)
INVLD	= 0
;---------------------------------------------------------------------------
; Used and not last data segment
NOTLST	= BT.15
UNLST	= BT.15!BT.14
;---------------------------------------------------------------------------
; Bits defined for Transmit status word #1
TS.1GE	= BT.14	; indicates an error
TS.1CE	= BT.12	; indicates loss of carrier
TS.1ES	= BT.10	; indicates that the sanity timer was ...
		; ... enabled via switch S4 at powerup
TS.1AE	= BT.09	; indicates that the transmission was ...
		; ... aborted due to excessive collisions
;
; Bits defined for Receive status word #1
RS.1GE	= BT.14	; indicates an error
RS.1ES	= BT.13	; indicates a looped back Setup or ...
		; ... External Loopback frame
RS.1DR	= BT.12	; Discard - indicates that OVF (bit 00), ...
		; ... CRCERR (bit 01), and SHORT (bit 03) are valid
RS.1RE	= BT.11	; RUNT error
RS.1BL	= BT.08!BT.09!BT.10 ; high order 3 bits of ...
			    ; ... receive byte length of frame
RS.1FE	= BT.02	; indicates a framing alignment error
RS.1CE	= BT.01	; indicates that a CRC error has been detected
;
; Bits defined for Receive status word #2
RS.2BL	= 377	; low order 8 bits of receive...
		; ...byte length of packet
;---------------------------------------------------------------------------
; Bits defined for DMAOP
DM.RDY	= BT.07	; Operation is completed
DM.NXM	= BT.06	; NMX error
DM.WRO	= BT.01	; DMA write operation
DM.RDO	= BT.00	; DMA read operation
;---------------------------------------------------------------------------
; Values defined for DMALDM
RX.BFS	= 1	; Select receive buffer
TX.BFS	= 2	; Select transmit buffer
BD.BFS	= 3	; Select BDL
;---------------------------------------------------------------------------
; Bits defined for various errors
PH.ERR	= BT.04	; Phy error
NX.ERR	= BT.03	; NXM error
BD.ERR	= BT.02	; Load BD ROM error
RX.ERR	= BT.01	; Receive error
TX.ERR	= BT.00	; Transmit error
;---------------------------------------------------------------------------
; Bits defined for BDL status
RX.BDL	= BT.07	; New Rx BDL
TX.BDL	= BT.06	; New Tx BDL
ST.BDL	= 4	; Status words offset
;---------------------------------------------------------------------------
; Bits defined for Ethernet ECTST register
;FR.MOP	= BT.15	; MOP frame
;FR.ECT	= BT.14	; ECT frame
ET.RDY	= BT.00	; Packet has been received
ET.TXD	= BT.01	; Transmit operation has been completed
ET.TRD	= BT.01	; Ready to transmit
ET.STP	= BT.02	; Setup packet
ET.SKB	= BT.03	; Skip byte
ET.MCT	= BT.04	; Multicast mode
ET.PRM	= BT.05	; Promiscuous mode
ET.REN	= BT.06	; Receiver is enabled
ET.INL	= BT.07	; Internal loopback mode
ET.IEL	= BT.08	; Internal-external loopback mode
ET.EXL	= BT.09	; External loopback mode
ER.RXR	= BT.10	; General receive error
ER.TXR	= BT.11	; General transmit error
ER.CRS	= BT.12	; Loss of carrier error
ER.RNT	= BT.13	; Runt error
ER.CRC	= BT.14	; Receive CRC error
ER.SHT	= BT.15	; Small frame error
ET.NIL	= ET.STP!ET.EXL!ET.IEL
ET.LOP	= ET.NIL!ET.INL
ET.REI	= ER.SHT!ER.CRC!ER.RNT
;ET.REI	= ER.CRC!ER.RNT
;ER.RER	= ER.CRC!ER.RNT!ER.RXR
ER.RER	= RS.1RE!RS.1DR!RS.1FE!RS.1CE
;---------------------------------------------------------------------------
; Bits defined for EGMOD
BD.ROM	= BT.15	; Load BDROM
ST.RST	= BT.04	; Sanity timer reset
ST.ENA	= BT.03	; Sanity timer enable
EA.LD3	= BT.02
EA.LD2	= BT.01
EA.LD1	= BT.00
EA.LED	= BT.00!BT.01!BT.02 ; LED bits
;---------------------------------------------------------------------------
; Bits defined for MD ops
MD.RDY	= BT.15	; Ready bit
MD.WR	= BT.06	; Write/read bit
MD.OP	= BT.05	; Start operation
MD.REG	= 37	; Register bits
MD.SRS	= 100000; Software reset
MD.LNK	= 400	; Link is ready
MD.RCV	= 1000	; Receiver is ready
MD.SPD	= 160000; Speed & duplex bits
;

	.SBTTL	- Constant definitions
;===========================================================================
; Packet sizez
;
EPMAXS	= 1514.	; Maximum ethernet packet size
EPMINS	= 60.	; Minimum ethernet packet size
;

	.SBTTL	- Macro definition
;===========================================================================
; Macro definition
;
	.MACRO	IV, OFFSET, ADR
	.	= OFFSET
	.IF	NB, <ADR>
		.WORD	ADR
	.IFF
	.WORD	START
	.ENDC
	.WORD	340		; PS=340
	.ENDM
;
	.SBTTL	- Interrupt vectors table
;---------------------------------------------------------------------------
; Generate interrupt vectors table
;
	.ASECT
	. = 0
	IV	0
	IV	4
	IV	10
	IV	14
	IV	20
	IV	24
	IV	30
	IV	34
	IV	40
	IV	44
	IV	50
	IV	54
	IV	60
	IV	64
	IV	70
	IV	74
	IV	100, TMRIRQ	; 100 Timer 50Hz
;
	.SBTTL	Main routines
	.SBTTL	- Start point (initial settings)
;===========================================================================
; Start
;
START:
	MOV	#RAMTOP, SP	; SP is on the top
;
; Initial settings
;
;	BIS	#1, @#LQABAS	; Block external access to the bus
	MTPS	#0		; Enable interrupt processing
; Init MAC address table by FF:FF:FF:FF:FF:FF
	MOV	#MACTAB, R4	; Initial address of the table
	MOV	#39., R5	; 39 words (13 addresses)
	ADD	#6, R4		; 2-nd entry (FF)
2$:	MOV	#177777, (R4)+	; Fill 2-nd address
	SOB	R5, 2$
; Get and store source mac address, init first MAC table entry
	MOV	#ESADR, R4	; Address of the SA ROM
	MOV	#MACTAB, R3	; Address of the MACTAB
	MOV	#SYSSRC, R5	; Address of the varible to store source mac
	MOV	#3, R0		; Number of words
6$:	MOV	(R4), (R3)+	; Write to MACTAB
	MOV	(R4)+, (R5)+	; Write to SYSSRC
	SOB	R0, 6$
;
.IF NE ETHINI
; Init Ethernet PHY
	CALL	DELAY
	CALL	MDCINI		; Init ethernet transceiver
	BCC	10$
	HALT			; !!! Error !!!
.ENDC
; Init MAC table
10$:	BIS	#ET.STP,@#ECTST	; Set S-bit in the register
	CALL	ETHTBP
	BIC	#ET.STP,@#ECTST	; Clear S-bit in the register
; Final initialization
20$:	MOV	#32., @#DMATIM	; Set DMA timeout value
	MOV	#BDLBAS, R1	; Initial BDL local address to R1
	MOV	#DMAOP, R2	; DMAOP address to R2
	CLR	4(R2)		; Clear DMA local device multiplexer
	MOV	#LQACSR, R3	; LQACSR address to R3
	MOV	#FLGVAL, @R1	; Init first BDL word
	CALL	SNTRES		; Reset sanity timer
	BISB	#RX.BDL, PRCFLG	; Initialize new Rx BDL flag
;	BIC	#1, @#LQABAS	; Unblock external access to the bus
.IF NE DBGINF
	CLRB	DBGNUM
.ENDC
.IF NE STATNM
	INC	STRSTN
.ENDC
;
	.SBTTL	- Main loop
;---------------------------------------------------------------------------
; Main loop
;
MLOOP:	BIT	#CS.XL, @R3	; Check XL-bit
	BNE	1$		; If not ready - continue
	CALL	TXP		; Else - call transmit operation
1$:	BIT	#ET.RDY,@#ECTST	; Is there new data frame?
	BEQ	2$		; No - continue
	CALL	RXP		; Else - call receive operation
	BR	MLOOP
2$:	TST	@#EGMOD		; Ready to load BD ROM?
	BPL	MLOOP		; No - continue
	CALL	PBDROM		; Yes - let's do it
	BR	MLOOP		; Loop
;
	.SBTTL	- Transmit operation
;===========================================================================
;
TXP:	MOV	@#LQATLL, TBDLL	; Get initial Tx BDL low order address bits
	MOV	@#LQATLH, TBDLH	; Get initial Tx BDL high order address bits
;-----------------------------------------------
; Init status word templates
	MOV	#20000, STW1	; Init status word 1 (bit 13 is always set)
	MOV	#1, STW2	; Init status word 2 (non zero TDR)
; Check Internal loopback mode
	BIT	#ET.INL, @#ECTST
	BEQ	TXL$
	BIS	#400, STW1	; Set bit 8 in the 1 status word
;===============================================
; Get first/next BDL block data
TXL$:	MOV	TBDLL, 6(R2)	; Set to DMA address (low order bits)
	MOV	TBDLH, 10(R2)	; Set DMA address (high order bits)
	MOV	#TBDLL, R0	; Address of the BDLL to R0 (for chain op)
	CALL	GETBDL		; Get BDL data
	BCC	1$
	JMP	28$		; If error - br to error proc.
;-----------------------------------------------
; Process V-bit
1$:	BIT	#AD.V, 2(R1)	; Check valid bit
	BNE	2$		; There is V-bit - continue
	BIS	#CS.XL, @R3	; No V-bit - set XL bit in the CSR ...
	JMP	32$		; ... and br to finish
;-----------------------------------------------
; S-bit processing
2$:	BIT	#AD.S, 2(R1)	; Is the S-bit set?
	BEQ	4$		; No - br to contin
	MOV	R4, R5		; Restore control ...
	NEG	R5		; ... control byte ...
	ASL	R5		; ... value
	BIT	#AD.L, 2(R1)	; Check for L-bit?
	BEQ	3$		; No L-bit -- continue
	INC	R5		; Restore multicast bit
3$:	MOVB	R5, SETUPB	; Save copy to variable
	BIC	#177, R5	; Leave only byte count
	NEG	R5		; 2-S compl.
	MOV	#20014, STW1	; Prepare setup packet ...
	MOV	#4140, STW2	; ... status words
	NEG	R4		; Eliminate control ...
	BIC	#77, R4		; ... bits from ...
	NEG	R4		; word count
	MOV	R4, 2(R2)	; Set word count for DMA transfer
	BIS	#ET.STP,@#ECTST	; Set S-bit in the emode register
	BR	5$
; Normal operation -- byte counter calc.
4$:	MOV	R4, R5
	ASL	R5
	BIT	#AD.L, 2(R1)	; Check for L-bit?
	BEQ	5$		; No L-bit - continue
	INC	R5		; Installed L-bit - decrease value
;-----------------------------------------------
; DMA transfer
5$:	MOV	#TX.BFS, 4(R2)	; Select TX for DMA operation
	CALL	DMASWR		; DMA write operation
	MOV	#0, 4(R2)	; Deselect local DMA device
	BCC	10$		; Got data without error, br to continue
	JMP	28$		; Got data with error, br to finish
;-----------------------------------------------
; Store byte count in the register and make copy
10$:	MOV	R5, @#ECNTB	; Store byte count in the register.
	MOV	R5, BCOUNT	; Save copy
;-----------------------------------------------
; E-bit
	BIT	#AD.E, 2(R1)	; Execute the packet?
	BNE	12$		; Yes - transmit data
	MOV	STW1, R4
	BIS	#UNLST, R4	; No - set bits in the 1-st status word ...
	BR	22$		; ... and send status words to the host
;-----------------------------------------------
; Transmit frame data
12$:	CALL	SNTRES		; Reset sanity timer
	MOV	#ECTST, R0
	BIS	#ET.TRD,@R0	; Set "ready-to-transmit" bit
14$:	BIT	#<ET.TXD!ER.TXR>,@R0 ; Transmitted or error?
	BEQ	14$		; Not yet, loop
;-----------------------------------------------
; Error checking
	BIC	#ET.TRD, @R0	; Clear "ready-to-transmit" bit
	BIT	#ER.TXR, @R0	; Got an error?
	BEQ	16$
	MOV	STW1, R4
	BIS	#<TS.1GE!TS.1CE!TS.1AE>,R4 ; Set error bits
.IF NE STATNM
	INC	STTXER
.ENDC

	BR	22$
16$:	NOP
;-----------------------------------------------
; Loopback packet processing
;	BIT	#<ET.STP!ET.IEL!ET.EXL>,@R0
;	BEQ	21$
;	BIT	#CS.RL, @R3	; Is receive BDL ready?
;	BNE	21$		' No - skip processing
;; Timeout setting
;	MOVB	TTICK, R0	; Store current tick value
;	ADD	#30, R0		; Add delay
;	CMP	#60., R0	; More than 60?
;	BPL	18$		; No - continue
;	SUB	#60., R0	; Yes - subtract 60
;; Wait for the loopback packet
;18$:	BIT	#ET.RDY,@#ECTST	; Is there new data?
;	BNE	20$
;	CMPB	TTICK, R0	; Timeout?
;	BLT	18$		; No - loop
;	BR	21$		; Yes - skip proccessing
;20$:	MOV	STW1, -(SP)
;	MOV	STW2, -(SP)
;	CALL	RXP		; Receive loopback packet
;	MOV	(SP)+, STW2
;	MOV	(SP)+, STW1
;-----------------------------------------------
; Send status words
21$:	MOV	STW1, R4
22$:	MOV	STW2, R5
	MOV	#TBDLL, R0	; BDL address to R0
	CALL	STWPR		; Send status words to host
	BCS	28$		; Carry is set - NXM error
	BIS	#CS.XI, @R3	; Yes - set XI bit in the CSR
;-----------------------------------------------
; Calculate next BDL address
26$:	ADD	#12., TBDLL	; 6 words offset, ...
	ADC	TBDLH		; ... add carry bit ...
	JMP	TXL$		; ... and loop
;-----------------------------------------------
; Carry is set, NXM error.
28$:
.IF NE STATNM
	INC	STTXER
.ENDC
	BIS	#<CS.NI!CS.XL!CS.RL!CS.XI>,@R3 ; Set NI-bit in the CSR
;
; Return
32$:
	RETURN
;
	.SBTTL	- Receive operation
;===========================================================================
;
RXP:	BIT	#CS.RI, @R3	; Stil in process?
	BEQ	1$
	JMP	RXF$
1$:	BIT	#CS.RL, @R3	; Check RL-bit
	BEQ	RXB$		; RL=0 - continue
;	BISB	#RX.BDL, PRCFLG ; RL=1 - set new BDL flag ...
	JMP	RXF$		; RL=1 - abort processing
;-----------------------------------------------
; BDL regs preparation
RXB$:	CLR	LNGERR
	TSTB	PRCFLG		; New BDL?
	BPL	2$		; No - skip initial
	MOV	@#LQARLL, RBDLL	; Get initial Rx BDL low order address bits
	MOV	@#LQARLH, RBDLH	; Get initial Rx BDL high order address bits
	BICB	#RX.BDL, PRCFLG	; Clear new BDL flag
;-----------------------------------------------
; Get first BDL block data
2$:	MOV	RBDLL, 6(R2)	; Set to DMA address (low order bits)
	MOV	RBDLH, 10(R2)	; Set DMA address (high order bits)
	MOV	#RBDLL, R0	; Address of the RBDLL to R0 (for chain op)
	CALL	GETBDL		; Get BDL data
	BCC	3$		; No error - br to continue
	JMP	RER$		; There is error - br to error proc.
;-----------------------------------------------
; Check V-bit
3$:	BIT	#AD.V, 2(R1)	; Check valid bit
	BNE	4$		; There is V-bit - continue
	BIS	#CS.RL, @R3	; There is no - set RL bits in the CSR, ...
	JMP	RXF$		; ... and return
;===============================================
; We've got an ethernet frame and valid BDL - continue
4$:	MOV	@#ECTST, R4	; Get ethernet status
	MOV	@#RXCNF, R0	; Get ethernet byte count and flags
	MOV	R0, R5
	BIC	#174000, R0	; Clear all except byte count bits
	MOV	R0, DATBCN
;-----------------------------------------------
; Packet processing starts here
; Check packet size
5$:	ASH	#2, R5		; Put bits in right position
	BIC	#^C<ET.REI>, R5	; Clear all except needed bits
	BIS	R5, R4		; Combine error bits
;-----------------------------------------------
; Calculate number of words for DMA transfer
6$:	MOV	R0, R5		; Store it for futher use
	BNE	7$		; Number of received bytes is not zero - continue
.IF NE STATNM
	INC	STZRPL
.ENDC
	JMP	RXF$		; ... jump to finish
7$:	BIT	#BT.00, R5	; Is it even?
	BEQ	8$		; Yes - continue
	INC	R5		; No - make it even
8$:	ASR	R5		; Convert to word number
	MOV	R5, DATWCN	; Data set size in words
;-----------------------------------------------
; Process errors and prepare status words template
	CLR	R5		; Prepare template
;	BIT	#<ER.MAC!ER.RNT>,R4 ; Address match error or RUNT error?
	BIT	#ER.RNT,R4	; Address match error or RUNT error?
	BEQ	9$		; No - br to continue
	MOV	#RS.1RE, R5	; Yes - set RUNT bit
.IF NE STATNM
	INC	STRNTN
.ENDC
; Giant frame proc...
9$:	CMP	R0, #EPMAXS	; Is frame size less than or equal to max?
	BLE	11$		; Yes - br to small frame proc.
	BIT	#ET.LOP, R4	; No - is it loopback?
	BNE	11$		; Yes - skip small frame proc.
	MOVB	#200, LNGERR	; No - set error bit and ...
.IF NE STATNM
	INC	STGFN
.ENDC
; Small frame proc...
11$:	BIT	#ER.SHT, R4	; Is it short frame?
	BEQ	12$		; No - continue
	MOVB	#200, SHTERR
.IF NE STATNM
	INC	STSFN
.ENDC
12$:	BIT	#ER.CRC, R4	; Did we get CRC error?
	BEQ	16$		; No - continue
	BIS	#<RS.1DR!RS.1CE>,R5 ; Yes - set error bits
.IF NE STATNM
	INC	STCRER
.ENDC
16$:	BIT	#ET.LOP, R4	; Loopback packet?
	BNE	17$		; Yes - br to process loopback
	SUB	#60., R0	; No - modify byte count ...
	BR	18$		; ... and br to continue
17$:	BIT	#ET.NIL, R4	; Avoid to set loopback bit in case of ...
	BEQ	18$		; ... internal loopback mode
	BIS	#RS.1ES, R5	; Set loopback packet bit
	BIT	#ET.STP, R4	; Is it setup packet?
	BEQ	18$		; No - br to finish template preparation
	BIS	#3400, R5	; Yes - set bits 10:08 and ...
	CALL	SPACK		; ... process setup packet
	BIC	#ET.STP,@#ECTST	; Clear S-bit in the emode register
	MOVB	SETUPB, R0	;
	BCS	RER$		; Br to error proc. in case of Carry-bit
18$:	MOVB	R0, STW2	; Save low bits of the byte count ...
	MOVB	R0, STW2+1	; ... value in the  2-ns status word
	BIC	#^C<RS.1BL>, R0	; Clear all except high bits and ...
	BIS	R0, R5		; ... set it in the template
	MOV	R5, STW1	; Store 1-st status word
;-----------------------------------------------
; Calculate word count for the current transfer
RXL$:	MOV	DATWCN, R4	; Data size in words to R4
	ADD	WCOUNT, R4	; Compare size of received data and ...
				; ... DMA data buffer size
	BLE	4$
;
; Size of received data is greater than DMA data buffer size
	MOV	R4, DATWCN	; Store size of the reminder for the futher step(s)
	MOV	WCOUNT, R5	; Use WCOUNT for DMA operation ...
	MOV	R5, 2(R2)	; ... and write it to the DMA register
	BR	5$		;
;
; Size of received data is less than (or equal to)... DMA data buffer size
4$:	MOV	DATWCN, R5	; Word counter
	NEG	R5		; 2's compl.
	MOV	R5, 2(R2)	; Set DMA word counter register
	CLR	DATWCN		; Clear DATWCN (indication of the final step)
;-----------------------------------------------
; DMA transfer
5$:	MOV	#RX.BFS, 4(R2)	; Select RX for DMA operation
	CALL	DMASRD		; Start DMA operation
	MOV	#0, 4(R2)	; Deselect DMA device
	BCS	RER$		; Got error - br to finish
;-----------------------------------------------
; Status words processing
	MOV	STW1, R4	; Get 1-st status word
	TST	DATWCN		; Is this the last data set?
	BNE	7$		; No  - br to set "used" and not "last"
	BIT	#ER.RER, R4	; Did we get errors?
	BNE	6$		; Yes - br to set error bit
	TSTB	LNGERR		; No - did we get long frame error?
	BPL	10$		; No - br to continue
6$:	BIS	#RS.1GE, R4	; Yes - set error bit ...
	BR	10$		; ... and br to continue
7$:	BIS	#UNLST, R4	; Set "used" and not "last"
;-----------------------------------------------
; Send status words
10$:	MOV	STW2, R5	; Get 2-nd status word value
	MOV	#RBDLL, R0	; RBDL address to R0
	CALL	STWPR		; Send status words to host
	BCS	RER$		; Carry is set - NXM error
;-----------------------------------------------
; Calculate next RBDL address, decision to return
	ADD	#12., RBDLL	; Calculate next RBDL address ...
	ADC	RBDLH		; ... (just 6 words shift)
	TST	DATWCN		; Is this the last data set?
	BEQ	16$		; No -- loop
;===============================================
; Get next BDL block data
	MOV	RBDLL, 6(R2)	; Set to DMA address (low order bits)
	MOV	RBDLH, 10(R2)	; Set DMA address (high order bits)
	MOV	#RBDLL, R0	; Address of the RBDLL to R0 (for chain op)
	CALL	GETBDL		; Get BDL data
	BCS	RER$		; If error - br to error proc.
;-----------------------------------------------
; Check V-bit
	BIT	#AD.V, 2(R1)	; Check valid bit
	BNE	RXL$		; There is V-bit - continue
	BIS	#CS.RL, @R3	; There is no - set RL bits in the CSR, ...
	BISB	#RX.BDL, PRCFLG ; ... set new BDL flag ...
	BR	RXF$		; ... and return

16$:	BIS	#CS.RI, @R3	; Signal "reception is completed"
	BR	RXF$
;-----------------------------------------------
; Carry is set NXM error
RER$:
.IF NE STATNM
	INC	STRXER
.ENDC
	BIS	#<CS.NI!CS.XL!CS.RL!CS.XI>,@R3 ; Set NI-bit in the CSR
;
; Return
RXF$:	RETURN
;
	.SBTTL	- BD ROM operation
;===========================================================================
; Algorithm
; 1. Read block 1K words from ROM to TX buffer.
; 2. Transfer.
; 3. Read block 1K words from ROM to TX buffer.
; 4. Transfer.
;
PBDROM:	BIT	#CS.RL, @R3	; Check RL-bit
	BEQ	1$		; RL=0 - continue
	JMP	PBDEX$		; RL=1 - exit
1$:	MOV	R2, -(SP)
	CALL	SNTRES		; Reset sanity timer
;-----------------------------------------------
; Rewrite from ROM to TX buffer
	MOV	#BDROM, R4	; BD ROM address to R4
	MOV	#TXBUF, R5	; TX buffer address to R5
	MOV	#BDRSIZ, R0	; Get BD ROM size in bytes ...
	ASR	R0		; ... and conver to words
	MOV	R0, BCOUNT	; Save copy
	MOV	R0, R2
	NEG	R2
;-----------------------------------------------
; Rewrite first part of BD ROM to TX buffer
	MOV	R2, @#ECNTB	; Store byte count in the register.
	ASR	R0		; Divided by 2
2$:	MOV	(R4)+, @R5	; Rewrite first part of BD ROM data
	SOB	R0, 2$		; to TX buffer
;-----------------------------------------------
; Transmit data
	MOV	#ECTST, R0
	BIS	#ET.TRD,@R0	; Set "ready-to-transmit" bit
3$:	BIT	#<ET.TXD!ER.TXR>,@R0 ; Transmitted or error?
	BEQ	3$		; Not yet, loop
	BIC	#ET.TRD, @R0	; Clear "ready-to-transmit" bit
;-----------------------------------------------
; Rewrite second part of BD ROM to TX buffer
	MOV	BCOUNT, R0
	MOV	R2, @#ECNTB	; Store byte count in the register.
	ASR	R0		; Divided by 2
4$:	MOV	(R4)+, @R5	; Rewrite second part of BD ROM data
	SOB	R0, 4$		; to TX buffer
;-----------------------------------------------
; Transmit data
	MOV	#ECTST, R0
	BIS	#ET.TRD,@R0	; Set "ready-to-transmit" bit
5$:	BIT	#<ET.TXD!ER.TXR>,@R0 ; Transmitted or error?
	BEQ	5$		; Not yet, loop
	BIC	#ET.TRD, @R0	; Clear "ready-to-transmit" bit
;-----------------------------------------------
; BD ROM is in Rx FIFO now
	MOV	(SP)+, R2
;
;-----------------------------------------------
; Start data transfer
	MOV	#2, DATADR
	MOV	@#LQARLL,RBDLL	; Get initial Rx BDL low order address bits
	MOV	@#LQARLH,RBDLH	; Get initial Rx BDL high order address bits
	MOV	#BDRSIZ, R5
	MOV	R5, BCOUNT	; Data set size in bytes
	ASR	R5
	MOV	R5, DATWCN	; Data set size in words
;
; Get first/next BDL block data
PBDLC$:	MOV	RBDLL, 6(R2)	; Set to DMA address (low order bits)
	MOV	RBDLH, 10(R2)	; Set DMA address (high order bits)
	MOV	#RBDLL, R0	; Address of the BDLL to R0 (for chain op)
	CALL	GETBDL		; Get BDL data
	BCS	100$		; If error - br to error proc.
;
; Process V-bit
	BIT	#AD.V, 2(R1)	; Check valid bit
	BNE	1$		; There is V-bit - continue
	BIS	#<CS.RL!CS.RI>,@R3 ; Set RL-bit in the CSR
	BR	PBDEX$		; There is no V-bit - return
;
; Calculate word count
1$:	MOV	@#RXCNF, R0	; Get ethernet byte count and flags
;	BIC	#174000, R0	; Clear all except byte count bits
; To compare received number of bytes with DATBCN/2 ?
	MOV	WCOUNT, 2(R2)	;
;
; DMA transfer
9$:	BIS	#RX.BFS,4(R2)	; Select receive buffer
	CALL	DMASRD		; Start DMA operation
	MOV	#0, 4(R2)	; Deselect DMA device
	BCS	100$		; Got error - br to finish
;
; Prepare and send status words
	MOV	#<UNLST!RS.1ES>, R4
	DEC	DATADR
	BNE	10$
	MOV	@#RXCNF, R0	; Blank reading
	MOV	#<NOTLST>, R4
10$:	CLR	R5		;
	MOV	#RBDLL, R0	; BDL address to R0
	CALL	STWPR		; Send status words to host
	BCS	100$		; Carry is set - NXM error
;
; Calculate next BDL address
	ADD	#12., RBDLL	; 6 words offset, ...
	ADC	RBDLH		; ... add carry bit ...
	BR	PBDLC$		; ... and loop
;-----------------------------------------------
; Carry is set NXM error
100$:
.IF NE STATNM
	INC	STBDER
.ENDC
	BIS	#<CS.NI!CS.XL!CS.RL!CS.XI>,@R3 ; Set NI-bit in the CSR
;
PBDEX$:	RETURN
;
	.SBTTL	Internal routines
	.SBTTL	- BDL processing
;===========================================================================
; Input:  R0 = Address of the BDLL buffer (used for chain op)
; Output: R4 - Word count
;
GETBDL:
1$:	CLR	16(R1)		; Init local address register
	MOV	#BD.BFS, 4(R2)	; Select BDL for DMA operation
	MOV	#-1, 2(R2)	; Process 1 word
	CALL	DMASRD		; Start DMA read operation
	BCC	2$		; Return if error
	MOV	#0, 4(R2)	; Deselect DMA device (DO NOT TOUCH Carry)
	BR	4$
2$:	MOV	#-3, 2(R2)	; Process 3 words
	CALL	DMASWR		; DMA write operation
	MOV	#0, 4(R2)	; Deselect DMA device (DO NOT TOUCH Carry)
.IF NE STATNM
	BCC	3$
	INC	STBDLE
	BR	5$
.IFF
	BCS	5$		; Return if error
.ENDC
;
; Get and store BDL data
3$:	MOV	2(R1), 10(R2)	; Store high order address bits
	MOV	4(R1), 6(R2)	; Store low order address bits
;
; Process C-bit
	BIT	#AD.C, 2(R1)	; Check chain bit
	BEQ	4$		; No bit - continue
	MOV	2(R1), 2(R0)	; Save copy of the high order address bits
	MOV	4(R1), (R0)	; Save copy of the low order address bits
	BR	1$		; Continue from the beginning
;
; Finalize operation
4$:	MOV	6(R1), R4	; Get buffer's word count
	MOV	R4, 2(R2)	; Store word count for futher DMA operations
	MOV	R4, WCOUNT	; Save copy
5$:	RETURN
;
	.SBTTL	- DMA processing
;===========================================================================
;
DMASRD:
	BIS	#DM.RDO,@R2	; Set read operation
	BR	DMAC$		; BR to main loop
DMASWR:
	BIS	#DM.WRO,@R2	; Set write operation
;
; Waiting for the DMA operation will be completed
DMAC$:	CLC			; Clear carry
1$:	BIT	#DM.RDY,@R2	; Ready?
	BEQ	1$		; Not yet - loop
	BIT	#DM.NXM,@R2	; NXM error?
	BEQ	2$		; No - normal exit
.IF NE STATNM
	INC	STNXER
.ENDC
	SEC			; Yes - set carry
2$:	BIC	#<DM.RDO!DM.WRO>,@R2 ; Clear operation bits
	RETURN
;
	.SBTTL	- Status words processing
;===========================================================================
; R0 = address of the BDLL buffer
; R4 = first status word
; R5 = second status word
;
STWPR:	MOV	R4, 10(R1)	; First status word
	MOV	R5, 12(R1)	; Second status word
	MOV	(R0)+, R4	; Get low order address bits
	MOV	(R0), R5	; Get high order address bits
	ADD	#8., R4		; Calculate memory address ...
	ADC	R5		; ... to store status words
	MOV	R4, 6(R2)	; Set low order address bits
	MOV	R5, 10(R2)	; Set high order address bits
	MOV	#ST.BDL, 16(R1)	; Set BDL local address offset
	MOV	#BD.BFS, 4(R2)	; Select BDL for DMA op.
	MOV	#-2, 2(R2)	; Process 2 words
	CALL	DMASRD		; Start DMA read operation
	MOV	#0, 4(R2)	; Deselect DMA local device
	RETURN
;
	.SBTTL	- Setup packet processing
;===========================================================================
;
SPACK:	MOV	R0, -(SP)
	MOV	R1, -(SP)
	MOV	R2, -(SP)
	MOV	R3, -(SP)
	MOV	R4, -(SP)
	MOV	R5, -(SP)
;-----------------------------------------------
; Process setup control byte
;
	MOVB	SETUPB, R5	; Get the initial value
	BIC	#177400, R5	; Clear high bits
	MOV	@#EGMOD, R1	; Get ether general register value
	BIC	#^C<EA.LED>, R1	; Prepare template register
; Promisc. and mcast bits
	MOV	R5, R4
	BIC	#^C<3>, R4	; Clear all except needed bits
	ASH	#5, R4		; Shit to right position
	BIS	R4, @#ECTST	; Set Mcast & Promis bits in the template
; Turn off LED bits
2$:	MOV	R5, R4
	ASH	#-2, R4		; Shift to the right position
	BIC	#^C<3>, R4	; Clear all except needed bits
	BICB	LEDS(R4), R1	; Turn off correct LED
;
; Set initial sanity timer value
	MOV	R5, R4		; Get setup byte value
	BIC	#177610, R4	; Clear all except needed bits
	ASH	#-3, R4		; Remove unused bits
	MOV	SNTIV(R4),SNTVAL ; Store initial value
;
; Sanity timer STM.ENA <= CS.SE
	BIT	#CS.SE,@#LQACSR	; Check CSR.SE bit
	BEQ	4$		; If 0, no operation
	BIS	#ST.ENA, R1	; Enable sanity timer
; Set register
4$:	MOV	R1, @#EGMOD	; Move the result to the register

;-----------------------------------------------
; Procerss MAC part
10$:	BIC	#177, R5	; Clear control bits
	BEQ	20$		; No MAC info - return
	CALL	ETHTAB		; Process MAC target addresses
;-----------------------------------------------
; Return
20$:	MOV	(SP)+, R5
	MOV	(SP)+, R4
	MOV	(SP)+, R3
	MOV	(SP)+, R2
	MOV	(SP)+, R1
	MOV	(SP)+, R0
.IF NE STATNM
	INC	STSTPN
.ENDC
	RETURN
;
	.SBTTL	- Populate ethernet filter table
;===========================================================================
;
ETHTAB:	MOV	#MACTAB, MTADR
	MOV	#RXBUF, R1	; Address of the receive buffer
	MOV	2(R1), ADRVAL	; Get and store FIFO address value
	MOV	#2, R5		; 2 groups
10$:	MOV	#6, R4		; 6 bytes for each address

12$:	MOV	MTADR, R2	; Address in the memory block
	MOV	#3, R3		; 3 words to read
	MOV	@R1, R0		; Get first word
	SWAB	R0		; Skip first byte
	MOVB	R0, @R2		; Store address byte
14$:	MOV	@R1, R0		; Get next word
	ADD	#6, R2		; Shift memory address
	MOVB	R0, @R2		; Store address byte
	ADD	#6, R2		; Shift memory address
	SWAB	R0		; Next byte
	MOVB	R0, @R2		; Store address byte
	SOB	R3, 14$		; Loop
;
	INC	MTADR		; Shift memory address
	SOB	R4, 12$		; Loop over the number of bytes ...
				; ... in the address
	INC	R2		; Next memory byte address
	MOV	R2, MTADR
; Loop to skip empty data block
	MOV	#10, R2		; Skip zero region
16$:	MOV	@R1, R0
	SOB	R2, 16$
;
	SOB	R5, 10$		; Loop over the group number
;
	MOV	ADRVAL, 2(R1)	; Restore FIFO address value
;
ETHTBP:	MOV	#14., R0	; MACs counter
	MOV	#MACTAB, R1	; Local table address entry
	CLR	R2		; Initial MAC table address value
	MOV	#EMACA, R3	; DELQA/DEQNA MAC table address
1$:	MOV	R2, (R3)	; Write address
	MOV	(R1)+, 2(R3)	; Write low address section
	MOV	(R1)+, 4(R3)	; Write middle address section
	MOV	(R1)+, 6(R3)	; Write high address section
	INC	R2		; Point to next table value
	SOB	R0, 1$		; Loop
	MOV	#0, (R3)	; Clear address
;
.IF NE ETBCHK
;
; Compare filter table
	BIC	#EA.LED,@#EGMOD	; Light off all leds
	MOV	#14., R0	; MACs counter
	MOV	#MACTAB, R1	; Local table address entry
	CLR	R2
2$:	MOV	R2, (R3)	; Write address
	MOV	2(R3), R4	; Read low word
	MOV	(R1)+, R5	; Read from MACTAB
	CMP	R4, R5		; Is equal?
	BNE	3$		; No -- br to error
	MOV	4(R3), R4	; Read middle word
	MOV	(R1)+, R5	; Read from MACTAB
	CMP	R4, R5		; Is equal?
	BNE	3$		; No -- br to error
	MOV	6(R3), R4	; Read high word
	MOV	(R1)+, R5	; Read from MACTAB
	CMP	R4, R5		; Is equal?
	BNE	3$		; No -- br to error
	INC	R2		; Point to next table value
	SOB	R0, 2$		; Loop
	MOV	#0, (R3)	; Clear address
	CLC			; Indicate success
	RETURN
3$:	BIS	#EA.LED,@#EGMOD	; Light on all leds
.IF NE STATNM
	INC	STEMER
.ENDC
	SEC			; Indicate error
.IFF
	CLC
.ENDC
	RETURN
;
	.SBTTL	- Reset sanity timer
;===========================================================================
;
SNTRES:
	MOV	SNTVAL, SNTCV	; Set initial value
	CLRB	SNTCK
	RETURN
;
.IF NE ETHINI
	.SBTTL	- Init ethernet transceiver
;===========================================================================
; Install one of the working modes.
; Return:
;    Carry is cleared	- no error, working mode is set
;    Carry is set	- error, could not set working mode
;
MDCINI:
;	CALL	MDSDLY
	CALL	MDWAIT
	BCS	6$
; Try to set working mode
	MOV	#MDINIV, R4	; Init values address
	MOV	#MDINIC, R5	; Init values counter
1$:	MOV	(R4), @#EMDVAL	; Set parameters for the mode
	CLR	R0		; Register number 0
	CALL	MDCWR		; Write data
	BCS	6$		; If carry - br to error processing
;
;	CALL	MDRST		; Reset device to activate the mode
;	BCS	6$		; If carry - br to error processing
;
	CLR	R0		; Register number 0x0
	CALL	MDCRD		; Read data
	BCS	6$		; If carry - br to error processing

	MOV	@#EMDVAL, R0	; Get MDC value
	CMP	R0, (R4)+
	BEQ	8$		; If equal - br to normal return
	SOB	R5, 1$		; If not - loop over all init values
6$:	BIC	#<EA.LD3!EA.LD2>,@#EGMOD ; Turn off/on ...
	BIS	#EA.LD1,@#EGMOD	; ... correct LEDs
.IF NE STATNM
	INC	STPHER
.ENDC
	SEC			; Set error flag
	TST	(PC)+
8$:	CLC			; Clear carry (normal return)
	RETURN
;---------------------------------------------------------------------------
; Read MDC value
; Parameter:
;    R0 - register number
;
MDCRD:	BICB	#^C<MD.REG>, R0	; Clear all except register bits
	BICB	#MD.WR, R0	; Clear write bit (read operation)
	BR	MDCOP		; Br to start
;---------------------------------------------------------------------------
; Write MDC value
; Parameter:
;    R0 - register number
;
MDCWR:	BICB	#^C<MD.REG>, R0	; Clear all except register bits
	BISB	#MD.WR, R0	; Set write bit (write operation)
;---------------------------------------------------------------------------
; MDC operation
; Parameter:
;    R0 - control byte
;
MDCOP:	BISB	#MD.OP, R0	; Set start bit ...
	MOVB	R0, @#EMDCTR	; ... and start operation
	CALL	MDWAIT		; Wait
	RETURN
;---------------------------------------------------------------------------
; Wait ready status. 50 ticks timeout
;
MDWAIT:	MOV	R1, -(SP)
	MOVB	TTICK, R0	; Store current tick value
	ADD	#50., R0	; Add delay
	CMP	#60., R0	; More than 60?
	BPL	1$		; No - continue
	SUB	#60., R0	; Yes - subtract 60
1$:	MOV	@#EMDCTR, R1	; Get MDC status
	TST	R1		; Operation complete when ...
	BPL	2$		; ... ready bit is set ...
	BIT	#40, R1		; ... and start bit is cleared
	BEQ	3$		; Condition met, br to normal return
2$:	CMPB	R0, TTICK	; Timeout?
	BNE	1$		; No - loop
.IF NE STATNM
	INC	STPHER
.ENDC
	SEC			; Yes - set error flag
	TST	(PC)+
3$:	CLC			; Clear carry
	MOV	(SP)+, R1
	RETURN
;---------------------------------------------------------------------------
; Reset ethernet PHY
;
MDRST:	MOV	R5, -(SP)
; Read BMCR and start reset operation
	CLR	R0		; Register number 0
	CALL	MDCRD		; Read data
	BCS	2$		; If carry - br to error processing
	MOV	@#EMDVAL, R0	; Get MDC value
	BIS	#MD.SRS, R0
	MOV	R0, @#EMDVAL	; Set software reset bit
	CLR	R0
	CALL	MDCWR		; Write data
	BCS	2$		; If carry - br to error processing
; Read BMCR and wait for the complete reset operation (BMCR.15=0)
	MOV	#177777, R5
1$:	CLR	R0		; Register number 0
	CALL	MDCRD		; Read data
	BCS	2$		; If carry - br to error processing
	TST	@#EMDVAL	; Check BMCR.15
	BPL	3$		; If 0 - br to normal return, ...
	SOB	R5, 1$		; ... else loop
2$:
.IF NE STATNM
	INC	STPHER
.ENDC
	SEC			; Set error flag...
	TST	(PC)+		; ... and return
3$:	CLC			; Clear error flag ...
	MOV	(SP)+, R5	; ... and return
	RETURN
.ENDC
;---------------------------------------------------------------------------
; Delay 1 seconds
;
DELAY:
	MOVB	TTICK, R0	; Store current tick value
	ADD	#30., R0	; Add delay
	CMP	#60., R0	; More than 60?
	BPL	1$		; No - continue
	SUB	#60., R0	; Yes - subtract 60
1$:	CMPB	TTICK, R0
	BNE	1$
	RETURN
.IF NE DBGINF
;
	.SBTTL	- Write debug information
;===========================================================================
; Write debug information.
;
DBGWRT:
	MOV	R5, -(SP)
;	INCB	DBGNUM
	MOV	DBGCAD, R5
	MOV	DBGFLG, (R5)+
	MOV	DBGOPR, (R5)+
	MOV	DBGVL1, (R5)+
	MOV	DBGVL2, (R5)+
	CMP	R5, DBGEAD	; End of debug buffer?
	BLT	1$		; No - continue
	MOV	#DBGDAT, R5	; Yes - beginning of the buffer to R0
1$:	MOV	R5, DBGCAD	; R0 to the current address
	MOV	(SP)+, R5
	RETURN
.ENDC
;
	.SBTTL	Timer interrupt handler
;===========================================================================
;
TMRIRQ:
;-----------------------------------------------
; Ticks
	INCB	TTICK		; Tics counter
	INCB	SNTCK
	CMPB	TTICK, #50.	; Got 50 tics?
	BNE	100$		; No - br to finish
	CLRB	TTICK		; Clear tics counter
;-----------------------------------------------
;  Seconds
	INCB	TSEC		; Increment seconds counter
	CMPB	TSEC, #60.	; Got 60 seconds?
	BNE	100$		; No - br to finish
	CLRB	TSEC		; Clear seconds counter
;-----------------------------------------------
; Minutes
	INCB	TMIN		; Increment minutes counter
	CMPB	TMIN,#60.	; Got 60 minutes?
	BNE	100$		; Not yet - br to RTI
	CLRB	TMIN		; Yes - clear minutes counter and ...
;-----------------------------------------------
; Process 5-ticks counter
100$:	BIT	#ST.ENA, @#EGMOD
	BEQ	110$
	CMPB	SNTCK, #5
	BNE	110$
	CLRB	SNTCK
	INC	SNTCV
	BNE	110$
;-----------------------------------------------
; Sanity counter is equal to zero
	BIS	#ST.RST,@#EGMOD ; Yes - generate BDCOK
;
110$:	RTI
;
	.SBTTL	Data section
;===========================================================================
;
SYSSRC:	.BLKB	6	; Source MAC address
MTADR:	.BLKW	1	; Address of the MACTAB entry
MACTAB:	.BLKB	84.	; Mac address table
DATADR:	.BLKW	1	; Data address offset
ADRVAL:	.BLKW	1	; Current read address in the receive FIFO
DATWCN:	.BLKW	1	; Current data size in words
DATBCN:	.BLKW	1	; Current data size in bytes
BCOUNT:	.BLKW	1	; Total data size in bytes
WCOUNT:	.BLKW	1	; DMA ops. data size (2's compl.)
RBDLL:	.BLKW	1	; Receive op BDL low address bits
RBDLH:	.BLKW	1	; Receve op BDL high address bits
TBDLL:	.BLKW	1	; BDL low address bits
TBDLH:	.BLKW	1	; BDL high address bits
STW1:	.BLKW	1	; 1-st status word
STW2:	.BLKB	1	; 2-nd status word
	.BLKB	1
.IF NE ETHINI
MDINIV:	.WORD	020400	; Ethernet init: 100 Mb, full duplex, no autoneg.
	.WORD	000400	; Ethernet init: 10 Mb, full duplex, no autoneg.
	.WORD	020000	; Ethernet init: 100 Mb, half duplex, no autoneg.
	.WORD	000000	; Ethernet init: 10 Mb, half duplex, no autoneg.
MDINIC	= <.-MDINIV>/2
MDRESV:	.WORD	060000	; Ethernet status: 100 Mb, full duplex
	.WORD	020000	; Ethernet status: 10 Mb, full duplex
	.WORD	040000	; Ethernet status: 100 Mb, half duplex
	.WORD	000000	; Ethernet status: 10 Mb, half duplex
.ENDC
;-----------------------------------------------
; Sanity timer
SNTIV:	.WORD	-3	; -0.3 sec (instead of 0.25)
	.WORD	-10.	; -1 sec
	.WORD	-40.	; -4 sec
	.WORD	-160.	; -16 sec
	.WORD	-600.	; -1 min
	.WORD	-2400.	; -4 min
	.WORD	-9600.	; -16 min
	.WORD	-38400.	; -64 min
SNTVAL:	.WORD	-2400.	; Initial value (-4 min.)
SNTCV:	.BLKW	1	; Current counter
SETUPB:	.BLKB	1	; Setup control word copy
SNTCK:	.BYTE	0	; 5-ticks counter
;-----------------------------------------------
; LEDS converter
LEDS:	.BYTE	0	; Leds - 000
	.BYTE	1	; Leds - 001
	.BYTE	2	; Leds - 010
	.BYTE	4	; Leds - 100
;-----------------------------------------------
; Flags
PRCFLG:	.BYTE	0	; BT.07 - New Rx BDL
			; BT.06 - New Tx BDL
			; BT.04 - Unused
			; BT.03	- Unused
			; BT.02	- Unused
			; BT.01	- Unused
			; BT.00	- Unused
	.EVEN
LNGERR:	.BYTE	0
SHTERR:	.BYTE	0
.IF NE STATNM
;-----------------------------------------------
;
STTXER:	.WORD	0	; Transmit errors
STRXER:	.WORD	0	; Receive errors
STBDER:	.WORD	0	; Load BD ROM error
STNXER:	.WORD	0	; NXM errors
STBDLE:	.WORD	0	; BDL errors
STEMER:	.WORD	0	; MACtab check errors
STPHER:	.WORD	0	; Phy error
STCRER:	.WORD	0	; CRC errors
STZRPL:	.WORD	0	; Zero length frames
STGFN:	.WORD	0	; Giant frames
STSFN:	.WORD	0	; Small frames
STRNTN:	.WORD	0	; Runt frames
STSTPN:	.WORD	0	; Setup packets
STRSTN:	.WORD	0	; Resets
.ENDC
;-----------------------------------------------
; Timer counters
TTICK:	.BYTE	0	; Ticks
TSEC:	.BYTE	0	; Seconds
TMIN:	.BYTE	0	; Minutes
;TCNT	= .-TTICK
	.EVEN
;
.IF NE DBGINF
;-----------------------------------------------
; Debug block
DBGFLG:	.WORD	125252
DBGOPR:	.BYTE	0
DBGNUM:	.BYTE	0
DBGVL1:	.WORD	0
DBGVL2:	.WORD	0
DBGCAD:	.WORD	DBGDAT
DBGEAD:	.WORD	DBGDAT+1200.
DBGDAT:	.BLKW	600.
.ENDC
;
	.END  0
